#!/usr/bin/env node
/**
 * Token compiler. One input, four generated-and-committed outputs:
 *
 *   packages/tokens/dist/theme.settings.json  — theme.json `settings` partial
 *   packages/tokens/dist/tokens.css           — :root custom properties
 *   packages/tokens/dist/defaults.ts          — typed control defaults for the editor
 *   themes/flagship/theme.json                — full theme.json (settings merged in)
 *
 * Run as a build step, never by hand. `--check` recompiles in memory and fails
 * if any committed output has drifted — that is the CI guard and the readable
 * review diff when a token changes.
 *
 * Usage:
 *   node packages/tokens/src/compile.mjs            # write outputs
 *   node packages/tokens/src/compile.mjs --check    # verify, exit 1 on drift
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG = join(HERE, '..');
const REPO = join(PKG, '..', '..');

const TOKENS_PATH = join(PKG, 'tokens.json');
const THEME_BASE_PATH = join(REPO, 'themes', 'flagship', 'theme.base.json');

const OUT = {
	themeSettings: join(PKG, 'dist', 'theme.settings.json'),
	css: join(PKG, 'dist', 'tokens.css'),
	defaults: join(PKG, 'dist', 'defaults.ts'),
	themeJson: join(REPO, 'themes', 'flagship', 'theme.json'),
};

const GENERATED_NOTE =
	'Generated by packages/tokens/src/compile.mjs — do not edit by hand.';

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

/**
 * Depth-first walk of a nested token object, yielding [ segments[], value ].
 *
 * @param {Object}   obj     Nested token object to walk.
 * @param {string[]} [trail] Path segments accumulated so far.
 */
function* leaves(obj, trail = []) {
	for (const [key, value] of Object.entries(obj)) {
		const next = [...trail, key];
		if (value && typeof value === 'object' && !Array.isArray(value)) {
			yield* leaves(value, next);
		} else {
			yield [next, value];
		}
	}
}

const kebab = (segments) => segments.join('-');

const camel = (segments) =>
	segments
		.map((seg, i) =>
			i === 0
				? seg.toLowerCase()
				: seg.charAt(0).toUpperCase() + seg.slice(1)
		)
		.join('');

const titleCase = (segments) =>
	segments.map((seg) => seg.charAt(0).toUpperCase() + seg.slice(1)).join(' ');

// ---------------------------------------------------------------------------
// generators
// ---------------------------------------------------------------------------

function buildCss(tokens) {
	const lines = [`/* ${GENERATED_NOTE} */`, ':root {'];
	for (const category of Object.keys(tokens)) {
		lines.push(`\t/* ${category} */`);
		for (const [segments, value] of leaves(tokens[category])) {
			lines.push(
				`\t--ledger-${kebab([category, ...segments])}: ${value};`
			);
		}
	}
	lines.push('}', '');
	return lines.join('\n');
}

function buildThemeSettings(tokens) {
	const palette = [];
	for (const [segments, color] of leaves(tokens.color)) {
		palette.push({
			slug: kebab(segments),
			name: titleCase(segments),
			color,
		});
	}

	const spacingSizes = Object.entries(tokens.space).map(([key, size]) => ({
		slug: key,
		name: `Space ${key}`,
		size,
	}));

	const fontSizes = Object.entries(tokens.size).map(([key, size]) => ({
		slug: key,
		name: key.toUpperCase(),
		size,
	}));

	const custom = {
		radius: { ...tokens.radius },
		shadow: { ...tokens.shadow },
		motion: { ...tokens.motion },
	};

	const settings = {
		appearanceTools: true,
		useRootPaddingAwareAlignments: true,
		layout: {
			contentSize: tokens.layout.content,
			wideSize: tokens.layout.wide,
		},
		// WP 7.1 responsive-style breakpoints. `@mobile` / `@tablet` style
		// variations (theme.json styles + block instances) are scoped by core
		// to `width <= viewport.mobile` and `viewport.mobile < width <=
		// viewport.tablet`. See ADR 0013.
		viewport: {
			mobile: tokens.viewport.mobile,
			tablet: tokens.viewport.tablet,
		},
		color: {
			defaultPalette: false,
			defaultGradients: false,
			defaultDuotone: false,
			customDuotone: false,
			palette,
		},
		spacing: {
			defaultSpacingSizes: false,
			units: ['px', 'rem', 'em', '%', 'vw', 'vh'],
			spacingSizes,
		},
		typography: {
			fluid: false,
			defaultFontSizes: false,
			fontSizes,
		},
		custom,
	};

	return {
		document: {
			$schema: 'https://schemas.wp.org/trunk/theme.json',
			version: 3,
			settings,
		},
		settings,
	};
}

function buildDefaults(tokens) {
	const controlDefaults = {};
	for (const category of Object.keys(tokens)) {
		for (const [segments, value] of leaves(tokens[category])) {
			controlDefaults[camel([category, ...segments])] = value;
		}
	}

	const controlLiteral =
		'{\n' +
		Object.entries(controlDefaults)
			.map(([key, value]) => `\t${key}: ${JSON.stringify(value)},`)
			.join('\n') +
		'\n}';

	const body = [
		`// ${GENERATED_NOTE}`,
		'',
		'/* eslint-disable */',
		'',
		`export const tokens = ${JSON.stringify(tokens, null, '\t')} as const;`,
		'',
		'export type Tokens = typeof tokens;',
		'',
		'/** Flat block-attribute defaults: camelCased token path -> value. */',
		`export const controlDefaults = ${controlLiteral} as const;`,
		'',
		'export type ControlDefaults = typeof controlDefaults;',
		'',
		'/** CSS custom-property name for a token path, e.g. cssVar("color", "brand", "500"). */',
		'export const cssVar = ( ...segments: string[] ): string =>',
		'\t`--ledger-${ segments.join( "-" ) }`;',
		'',
		'/** `var(--ledger-…)` reference for a token path. */',
		'export const cssVarRef = ( ...segments: string[] ): string =>',
		'\t`var(${ cssVar( ...segments ) })`;',
		'',
	];
	return body.join('\n');
}

function buildThemeJson(themeSettingsDoc) {
	let base;
	try {
		base = JSON.parse(readFileSync(THEME_BASE_PATH, 'utf8'));
	} catch {
		base = {};
	}
	const merged = {
		$schema: 'https://schemas.wp.org/trunk/theme.json',
		version: 3,
		...base,
		settings: themeSettingsDoc.settings,
	};
	// _generated marker sorts to the top so reviewers see it first.
	return { _generated: GENERATED_NOTE, ...merged };
}

// ---------------------------------------------------------------------------
// compile
// ---------------------------------------------------------------------------

/**
 * Pure: tokens object -> { path: string contents }.
 *
 * @param {Object} tokens Parsed tokens.json contents.
 */
export function compile(tokens) {
	const themeSettings = buildThemeSettings(tokens);
	return {
		[OUT.themeSettings]:
			JSON.stringify(themeSettings.document, null, '\t') + '\n',
		[OUT.css]: buildCss(tokens),
		[OUT.defaults]: buildDefaults(tokens),
		[OUT.themeJson]:
			JSON.stringify(buildThemeJson(themeSettings), null, '\t') + '\n',
	};
}

export function readTokens() {
	return JSON.parse(readFileSync(TOKENS_PATH, 'utf8'));
}

export const outputPaths = OUT;

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function main() {
	const check = process.argv.includes('--check');
	const artefacts = compile(readTokens());
	let drift = 0;

	for (const [path, contents] of Object.entries(artefacts)) {
		const rel = relative(REPO, path).replace(/\\/g, '/');
		if (check) {
			let current = null;
			try {
				current = readFileSync(path, 'utf8');
			} catch {
				current = null;
			}
			if (current !== contents) {
				drift += 1;
				process.stderr.write(
					`  drift: ${rel} is out of sync with tokens.json\n`
				);
			}
		} else {
			writeFileSync(path, contents);
			process.stdout.write(`  wrote ${rel}\n`);
		}
	}

	if (check && drift > 0) {
		process.stderr.write(
			`\n${drift} generated file(s) stale. Run \`pnpm run tokens:build\` and commit.\n`
		);
		process.exit(1);
	}
	if (check) {
		process.stdout.write('  tokens: all generated files in sync\n');
	}
}

if (
	import.meta.url === `file://${process.argv[1]}` ||
	process.argv[1]?.endsWith('compile.mjs')
) {
	main();
}
